/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_Management;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author rashe
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bl = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        out = new javax.swing.JButton();
        bl2 = new javax.swing.JButton();
        bl1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 4, -1, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_close.setText("  X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });
        jPanel2.add(jLabel_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 30, 30));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_minimize.setText("  -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });
        jPanel4.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bl.setBackground(new java.awt.Color(0, 84, 140));
        bl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 255, 255));
        bl.setText("To Do");
        bl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blMouseExited(evt);
            }
        });
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });
        jPanel3.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 200, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 530, 320));

        time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        time.setText("Time");
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 140, 40));

        date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date.setText("Date");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 190, 40));

        out.setBackground(new java.awt.Color(255, 0, 51));
        out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setText("Log Out");
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outMouseExited(evt);
            }
        });
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        jPanel3.add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 200, 40));

        bl2.setBackground(new java.awt.Color(0, 84, 140));
        bl2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl2.setForeground(new java.awt.Color(255, 255, 255));
        bl2.setText("Change Password");
        bl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bl2MouseExited(evt);
            }
        });
        bl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bl2ActionPerformed(evt);
            }
        });
        jPanel3.add(bl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 200, 40));

        bl1.setBackground(new java.awt.Color(0, 84, 140));
        bl1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl1.setForeground(new java.awt.Color(255, 255, 255));
        bl1.setText("About");
        bl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bl1MouseExited(evt);
            }
        });
        bl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bl1ActionPerformed(evt);
            }
        });
        jPanel3.add(bl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 200, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1050, 460));

        setSize(new java.awt.Dimension(1051, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseEntered

    }//GEN-LAST:event_outMouseEntered

    private void outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseExited

    }//GEN-LAST:event_outMouseExited

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        Login_Form form = new Login_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_outActionPerformed

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed
        Menu_Form form = new Menu_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_blActionPerformed

    private void blMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseExited

    }//GEN-LAST:event_blMouseExited

    private void blMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseEntered

    }//GEN-LAST:event_blMouseEntered

    private void bl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bl2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bl2MouseEntered

    private void bl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bl2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bl2MouseExited

    private void bl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bl2ActionPerformed
        change_pass form = new change_pass();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bl2ActionPerformed

    private void bl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bl1MouseEntered

    private void bl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bl1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bl1MouseExited

    private void bl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bl1ActionPerformed
        Intro form = new Intro();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bl1ActionPerformed

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(label_border);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(label_border);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    /**
     * @param args the command line arguments
     */
    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH) + 1;
                        int year = cal.get(Calendar.YEAR);

                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        time.setText(hour + ":" + minute + ":" + second);
                        date.setText(day + ":" + month + ":" + year);

                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        };
        clock.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bl;
    private javax.swing.JButton bl1;
    private javax.swing.JButton bl2;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton out;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
