/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_Management;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author rashe
 */
public class Menu_Form extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Form
     */
    public Menu_Form() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ext = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bl = new javax.swing.JButton();
        br = new javax.swing.JButton();
        am = new javax.swing.JButton();
        out = new javax.swing.JButton();
        ab = new javax.swing.JButton();
        or = new javax.swing.JButton();
        em = new javax.swing.JButton();
        home = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setForeground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo4.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 100));

        date.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 220, 40));

        time.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("Time");
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, 240, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 110, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Time");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, 50));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ext.setForeground(new java.awt.Color(255, 255, 255));
        ext.setText("  X");
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extMouseExited(evt);
            }
        });
        jPanel2.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 40, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 0, 40, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 100));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bl.setBackground(new java.awt.Color(0, 84, 140));
        bl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(255, 255, 255));
        bl.setText("Book Lend");
        bl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                blMouseExited(evt);
            }
        });
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });
        jPanel1.add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 40));

        br.setBackground(new java.awt.Color(0, 84, 140));
        br.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        br.setForeground(new java.awt.Color(255, 255, 255));
        br.setText("Book Return");
        br.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brMouseExited(evt);
            }
        });
        br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brActionPerformed(evt);
            }
        });
        jPanel1.add(br, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 40));

        am.setBackground(new java.awt.Color(0, 84, 140));
        am.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        am.setForeground(new java.awt.Color(255, 255, 255));
        am.setText("Members");
        am.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                amMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                amMouseExited(evt);
            }
        });
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });
        jPanel1.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 40));

        out.setBackground(new java.awt.Color(255, 0, 51));
        out.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        out.setForeground(new java.awt.Color(255, 255, 255));
        out.setText("Log Out");
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                outMouseExited(evt);
            }
        });
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });
        jPanel1.add(out, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 250, 40));

        ab.setBackground(new java.awt.Color(0, 84, 140));
        ab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ab.setForeground(new java.awt.Color(255, 255, 255));
        ab.setText("Books");
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abMouseExited(evt);
            }
        });
        ab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abActionPerformed(evt);
            }
        });
        jPanel1.add(ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, 40));

        or.setBackground(new java.awt.Color(0, 84, 140));
        or.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        or.setForeground(new java.awt.Color(255, 255, 255));
        or.setText("Orders");
        or.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orMouseExited(evt);
            }
        });
        or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orActionPerformed(evt);
            }
        });
        jPanel1.add(or, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, 40));

        em.setBackground(new java.awt.Color(0, 84, 140));
        em.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        em.setForeground(new java.awt.Color(255, 255, 255));
        em.setText("Employe");
        em.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emMouseExited(evt);
            }
        });
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 730));

        home.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 1110, 730));

        setSize(new java.awt.Dimension(1397, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed

        home.removeAll();
        Borrow br = new Borrow();
        home.add(br).setVisible(true);

    }//GEN-LAST:event_blActionPerformed

    private void brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brActionPerformed
        home.removeAll();
        Return br = new Return();
        home.add(br).setVisible(true);
    }//GEN-LAST:event_brActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed

        home.removeAll();
        AddMember br = new AddMember();
        home.add(br).setVisible(true);

    }//GEN-LAST:event_amActionPerformed

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        Login_Form form = new Login_Form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_outActionPerformed

    private void abActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abActionPerformed
        home.removeAll();
        AddBook br = new AddBook();
        home.add(br).setVisible(true);
    }//GEN-LAST:event_abActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void extMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        ext.setBorder(label_border);
        ext.setForeground(Color.white);
    }//GEN-LAST:event_extMouseEntered

    private void extMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        ext.setBorder(label_border);
        ext.setForeground(Color.black);
    }//GEN-LAST:event_extMouseExited

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        dashboard form = new dashboard();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_extMouseClicked

    private void blMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseEntered
        bl.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_blMouseEntered

    private void blMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blMouseExited
        bl.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_blMouseExited

    private void brMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseEntered
        br.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_brMouseEntered

    private void amMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amMouseEntered
        am.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_amMouseEntered

    private void abMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseEntered
        ab.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_abMouseEntered

    private void brMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brMouseExited
        br.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_brMouseExited

    private void amMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amMouseExited
        am.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_amMouseExited

    private void abMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseExited
        ab.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_abMouseExited

    private void orMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orMouseEntered
        or.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_orMouseEntered

    private void orMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orMouseExited
        or.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_orMouseExited

    private void orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orActionPerformed
        home.removeAll();
        orders or = new orders();
        home.add(or).setVisible(true);
    }//GEN-LAST:event_orActionPerformed

    private void outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseExited
        out.setBackground(new Color(255, 0, 51));
    }//GEN-LAST:event_outMouseExited

    private void outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseEntered
        out.setBackground(new Color(255, 69, 0));
    }//GEN-LAST:event_outMouseEntered

    private void emMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emMouseEntered
        em.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_emMouseEntered

    private void emMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emMouseExited
        em.setBackground(new Color(0, 84, 140));
    }//GEN-LAST:event_emMouseExited

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        home.removeAll();
        employe em = new employe();
        home.add(em).setVisible(true);
    }//GEN-LAST:event_emActionPerformed

    public void clock() {
        Thread clock = new Thread() {
            public void run() {
                try {
                    while (true) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH) + 1;
                        int year = cal.get(Calendar.YEAR);

                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        time.setText(hour + ":" + minute + ":" + second);
                        date.setText(day + ":" + month + ":" + year);

                        sleep(1000);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        };
        clock.start();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ab;
    private javax.swing.JButton am;
    private javax.swing.JButton bl;
    private javax.swing.JButton br;
    private javax.swing.JLabel date;
    private javax.swing.JButton em;
    private javax.swing.JLabel ext;
    private javax.swing.JDesktopPane home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton or;
    private javax.swing.JButton out;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
