/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_Management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashe
 */
public class online extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    public online() {
        initComponents();
        conn = My_CNX.getConnection();
        tablelord();
        autoId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        nu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bcode = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addr = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        select = new javax.swing.JComboBox<>();
        order = new javax.swing.JButton();
        orno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 80, 40));

        bname.setEditable(false);
        bname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        jPanel1.add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Code :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        bcode.setEditable(false);
        bcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(bcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, 30));

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 90, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Your Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 110, 40));

        addr.setColumns(20);
        addr.setRows(5);
        jScrollPane2.setViewportView(addr);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 160, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 80, 40));

        select.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 90, 30));

        order.setBackground(new java.awt.Color(0, 51, 102));
        order.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        order.setForeground(new java.awt.Color(255, 255, 255));
        order.setText("Order");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderMouseExited(evt);
            }
        });
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 130, 40));

        orno.setEditable(false);
        orno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(orno, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1030, 160));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setBackground(new java.awt.Color(204, 204, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1025, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-Library");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 50));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ext.setText(" X");
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extMouseExited(evt);
            }
        });
        jPanel2.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 30, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Books");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 120, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 370));

        setSize(new java.awt.Dimension(1026, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Thanks for staying with us");
        this.dispose();
        welcome wl = new welcome();
        wl.setVisible(true);
    }//GEN-LAST:event_extMouseClicked

    private void extMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        ext.setBorder(label_border);
        ext.setForeground(Color.white);
    }//GEN-LAST:event_extMouseEntered

    private void extMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        ext.setBorder(label_border);
        ext.setForeground(Color.black);
    }//GEN-LAST:event_extMouseExited

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        String id = orno.getText();
        String bcd = bcode.getText();
        String bnm = bname.getText();
        String ynm = name.getText();
        String nub = nu.getText();
        String ad = addr.getText();
        String sel = select.getSelectedItem().toString();

        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "ID is Empty");
        } else if (bcd.equals("")) {
            JOptionPane.showMessageDialog(null, "Book Code is Empty");
        } else if (bnm.equals("")) {
            JOptionPane.showMessageDialog(null, "Book Name is Empty");
        } else if (ynm.equals("")) {
            JOptionPane.showMessageDialog(null, "Name is Empty");
        } else if (nub.equals("")) {
            JOptionPane.showMessageDialog(null, "Number is Empty");
        } else if (ad.equals("")) {
            JOptionPane.showMessageDialog(null, "Address is Empty");
        } else if (sel.equals("")) {
            JOptionPane.showMessageDialog(null, "select is Empty");
        } else {
            try {
                String sql = "INSERT INTO orders(order_no, book_code, book_name, cus_nam, cus_number, customer_add, quan) VALUES (?,?,?,?,?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.setString(2, bcd);
                pst.setString(3, bnm);
                pst.setString(4, ynm);
                pst.setString(5, nub);
                pst.setString(6, ad);
                pst.setString(7, sel);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "Successfully Order");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
            clearFild();
            tablelord();
            autoId();
        }


    }//GEN-LAST:event_orderActionPerformed

    private void orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseEntered
        order.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_orderMouseEntered

    private void orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseExited
        order.setBackground(new Color(0, 51, 102));
    }//GEN-LAST:event_orderMouseExited

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel) table.getModel();
        int selectrowindex = table.getSelectedRow();

        bcode.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        bname.setText(tmodel.getValueAt(selectrowindex, 1).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void autoId() {
        try {

            String sql = "SELECT order_no  FROM orders ORDER By order_no DESC";

            ps = (PreparedStatement) conn.prepareStatement(sql);
            rs = ps.executeQuery();
            if (rs.next()) {
                String rnno = rs.getString("order_no");
                int co = rnno.length();
                String txt = rnno.substring(0, 2);
                String num = rnno.substring(2, co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt + snum;
                orno.setText(ftxt);
            } else {
                orno.setText("ON1000");
            }

        } catch (NumberFormatException | SQLException e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }

    }

    private void tablelord() {

        try {

            String sql = "SELECT book_code, nam, publisher, price FROM addbook";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            table.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(rootPane, e);

        }

    }

    private void clearFild() {

        //  mid.setText("");
        bname.setText("");
        bcode.setText("");
        select.setSelectedIndex(0);
        addr.setText("");
        name.setText("");
        nu.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr;
    private javax.swing.JTextField bcode;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel ext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nu;
    private javax.swing.JButton order;
    private javax.swing.JTextField orno;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
