/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Library_Management;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author rashe
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ext = new javax.swing.JLabel();
        emp = new javax.swing.JButton();
        bu = new javax.swing.JButton();
        abt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("wellcome");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 130));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 70));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Version 0.3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 490));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setBackground(new java.awt.Color(0, 51, 255));
        min.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        min.setText("  -");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        jPanel4.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel3.add(jPanel4);
        jPanel4.setBounds(530, 0, 40, 40);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ext.setText("  X");
        ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extMouseExited(evt);
            }
        });
        jPanel2.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel3.add(jPanel2);
        jPanel2.setBounds(570, 0, 40, 40);

        emp.setBackground(new java.awt.Color(51, 0, 153));
        emp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        emp.setForeground(new java.awt.Color(255, 255, 255));
        emp.setText("Employee");
        emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                empMouseExited(evt);
            }
        });
        emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empActionPerformed(evt);
            }
        });
        jPanel3.add(emp);
        emp.setBounds(190, 130, 260, 60);

        bu.setBackground(new java.awt.Color(51, 0, 153));
        bu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bu.setForeground(new java.awt.Color(255, 255, 255));
        bu.setText("Online Buy");
        bu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buMouseExited(evt);
            }
        });
        bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buActionPerformed(evt);
            }
        });
        jPanel3.add(bu);
        bu.setBounds(190, 220, 260, 60);

        abt.setBackground(new java.awt.Color(51, 0, 153));
        abt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        abt.setForeground(new java.awt.Color(255, 255, 255));
        abt.setText("About us");
        abt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abtMouseExited(evt);
            }
        });
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });
        jPanel3.add(abt);
        abt.setBounds(190, 310, 260, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.jpg"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, -10, 620, 500);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 610, 490));

        setSize(new java.awt.Dimension(1028, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseClicked
        System.exit(0);
    }//GEN-LAST:event_extMouseClicked

    private void extMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        ext.setBorder(label_border);
        ext.setForeground(Color.white);

    }//GEN-LAST:event_extMouseEntered

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abtActionPerformed

    private void buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buActionPerformed
        online br = new online();
        br.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buActionPerformed

    private void empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empActionPerformed

        Login_Form br = new Login_Form();
        br.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empActionPerformed

    private void empMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseEntered
        emp.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_empMouseEntered

    private void empMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empMouseExited
        emp.setBackground(new Color(51, 0, 153));
    }//GEN-LAST:event_empMouseExited

    private void buMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buMouseEntered
        bu.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_buMouseEntered

    private void buMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buMouseExited
        bu.setBackground(new Color(51, 0, 153));
    }//GEN-LAST:event_buMouseExited

    private void abtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtMouseEntered
        abt.setBackground(new Color(0, 101, 183));
    }//GEN-LAST:event_abtMouseEntered

    private void abtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abtMouseExited
        abt.setBackground(new Color(51, 0, 153));
    }//GEN-LAST:event_abtMouseExited

    private void extMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        ext.setBorder(label_border);
        ext.setForeground(Color.black);
    }//GEN-LAST:event_extMouseExited

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        min.setBorder(label_border);
        min.setForeground(Color.white);
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        min.setBorder(label_border);
        min.setForeground(Color.black);
    }//GEN-LAST:event_minMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abt;
    private javax.swing.JButton bu;
    private javax.swing.JButton emp;
    private javax.swing.JLabel ext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel min;
    // End of variables declaration//GEN-END:variables
}
